#############################################################################
# Makefile for building: Xcellule_mac.app/Contents/MacOS/Xcellule_mac
# Generated by qmake (3.1) (Qt 5.13.0)
# Project:  Xcellule_mac.pro
# Template: app
# Command: /sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/bin/qmake -o Makefile Xcellule_mac.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -stdlib=libc++ -std=c++11 -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtGui.framework/Headers -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/macx-clang -F/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib
QMAKE         = /sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Xcellule_mac1.0.0
DISTDIR = /Users/trobicho/project/otherProject/Xcellule/.tmp/Xcellule_mac1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib
LIBS          = $(SUBLIBS) -F/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib -framework GLUT -L$(HOME)/lib -lXcel -framework QtOpenGL -F/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtWidgets -F/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -F/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib -framework QtCore -framework DiskArbitration -framework IOKit -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		MainWin.cpp \
		Xcellule.cpp \
		GLtree.cpp \
		File_panel.cpp \
		WinGL.cpp moc_MainWin.cpp \
		moc_File_panel.cpp \
		moc_GLtree.cpp \
		moc_WinGL.cpp
OBJECTS       = main.o \
		MainWin.o \
		Xcellule.o \
		GLtree.o \
		File_panel.o \
		WinGL.o \
		moc_MainWin.o \
		moc_File_panel.o \
		moc_GLtree.o \
		moc_WinGL.o
DIST          = /sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/spec_pre.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/qdevice.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/device_config.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/unix.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/mac.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/macx.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/sanitize.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/gcc-base.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/clang.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/clang-mac.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/qconfig.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/qt_functions.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/qt_config.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/exclusive_builds.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/sdk.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/toolchain.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/toolchain.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/default_pre.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/default_pre.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/resolve_config.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/default_post.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/default_post.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/objective_c.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/qt.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/resources.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/moc.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/unix/opengl.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/uic.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/unix/thread.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/mac.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/warn_on.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/qmake_use.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/file_copies.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/rez.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/testcase_targets.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/exceptions.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/yacc.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/lex.prf \
		Xcellule_mac.pro Xcellule.h \
		MainWin.h \
		File_panel.h \
		GLtree.h \
		WinGL.h main.cpp \
		MainWin.cpp \
		Xcellule.cpp \
		GLtree.cpp \
		File_panel.cpp \
		WinGL.cpp
QMAKE_TARGET  = Xcellule_mac
DESTDIR       = 
TARGET        = Xcellule_mac.app/Contents/MacOS/Xcellule_mac

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.13
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/trobicho/project/otherProject/Xcellule/Xcellule_mac.pro


include /sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Xcellule_mac.app/Contents/MacOS/Xcellule_mac:  $(OBJECTS)  
	@test -d Xcellule_mac.app/Contents/MacOS/ || mkdir -p Xcellule_mac.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Xcellule_mac.pro /sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf /sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/spec_pre.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/qdevice.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/device_config.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/unix.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/mac.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/macx.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/sanitize.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/gcc-base.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/clang.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/clang-mac.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/qconfig.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/qt_functions.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/qt_config.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/exclusive_builds.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/sdk.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/toolchain.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/toolchain.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/default_pre.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/default_pre.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/resolve_config.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/default_post.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/default_post.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/objective_c.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/qt.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/resources.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/moc.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/unix/opengl.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/uic.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/unix/thread.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/mac.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/warn_on.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/qmake_use.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/file_copies.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/rez.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/testcase_targets.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/exceptions.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/yacc.prf \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/lex.prf \
		Xcellule_mac.pro \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtGui.framework/QtGui.prl \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Xcellule_mac.pro
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/spec_pre.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/qdevice.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/device_config.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/unix.conf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/mac.conf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/macx.conf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/sanitize.conf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/gcc-base.conf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/gcc-base-mac.conf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/clang.conf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/common/clang-mac.conf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/qconfig.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_charts.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_core.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_help.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_location.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_network.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_script.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webview.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/qt_functions.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/qt_config.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/exclusive_builds.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/sdk.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/toolchain.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/toolchain.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/default_pre.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/default_pre.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/resolve_config.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/default_post.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/default_post.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/objective_c.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/qt.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/resources.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/moc.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/unix/opengl.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/uic.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/unix/thread.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/mac.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/warn_on.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/qmake_use.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/file_copies.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/rez.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/testcase_targets.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/exceptions.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/yacc.prf:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/lex.prf:
Xcellule_mac.pro:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtGui.framework/QtGui.prl:
/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Xcellule_mac.pro

qmake_all: FORCE

Xcellule_mac.app/Contents/PkgInfo: 
	@test -d Xcellule_mac.app/Contents || mkdir -p Xcellule_mac.app/Contents
	@$(DEL_FILE) Xcellule_mac.app/Contents/PkgInfo
	@echo "APPL????" > Xcellule_mac.app/Contents/PkgInfo
Xcellule_mac.app/Contents/Resources/empty.lproj: 
	@test -d Xcellule_mac.app/Contents/Resources || mkdir -p Xcellule_mac.app/Contents/Resources
	@touch Xcellule_mac.app/Contents/Resources/empty.lproj
	
Xcellule_mac.app/Contents/Info.plist: 
	@test -d Xcellule_mac.app/Contents || mkdir -p Xcellule_mac.app/Contents
	@$(DEL_FILE) Xcellule_mac.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.Xcellule-mac,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.Xcellule-mac,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,Xcellule_mac,g" -e "s,@LIBRARY@,Xcellule_mac,g" -e "s,\$${EXECUTABLE_NAME},Xcellule_mac,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/macx-clang/Info.plist.app >Xcellule_mac.app/Contents/Info.plist

all: Makefile \
		Xcellule_mac.app/Contents/PkgInfo \
		Xcellule_mac.app/Contents/Resources/empty.lproj \
		Xcellule_mac.app/Contents/Info.plist Xcellule_mac.app/Contents/MacOS/Xcellule_mac

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Xcellule.h MainWin.h File_panel.h GLtree.h WinGL.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp MainWin.cpp Xcellule.cpp GLtree.cpp File_panel.cpp WinGL.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Xcellule_mac.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode $(EXPORT__PRO_FILE_)

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -stdlib=libc++ -std=c++11 -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -dM -E -o moc_predefs.h /sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_MainWin.cpp moc_File_panel.cpp moc_GLtree.cpp moc_WinGL.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWin.cpp moc_File_panel.cpp moc_GLtree.cpp moc_WinGL.cpp
moc_MainWin.cpp: MainWin.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		File_panel.h \
		GLtree.h \
		WinGL.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QtOpenGL \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglglobal.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglcolormap.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglframebufferobject.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglfunctions.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglpixelbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglversion.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget \
		../Xcel/Xcel.h \
		../Xcel/Celtree.h \
		../Xcel/Quadtree.h \
		../Xcel/pos2D.h \
		../Xcel/cel.h \
		../Xcel/Rules.h \
		../Xcel/Loader.h \
		../Xcel/LoaderRLE.h \
		../Xcel/Rules_totalistic.h \
		../Xcel/Rules_gol.h \
		moc_predefs.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/bin/moc
	/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/bin/moc $(DEFINES) --include /Users/trobicho/project/otherProject/Xcellule/moc_predefs.h -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/macx-clang -I/Users/trobicho/project/otherProject/Xcellule -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtGui.framework/Headers -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib MainWin.h -o moc_MainWin.cpp

moc_File_panel.cpp: File_panel.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		GLtree.h \
		WinGL.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QtOpenGL \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglglobal.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglcolormap.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglframebufferobject.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglfunctions.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglpixelbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglversion.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget \
		../Xcel/Xcel.h \
		../Xcel/Celtree.h \
		../Xcel/Quadtree.h \
		../Xcel/pos2D.h \
		../Xcel/cel.h \
		../Xcel/Rules.h \
		../Xcel/Loader.h \
		../Xcel/LoaderRLE.h \
		../Xcel/Rules_totalistic.h \
		../Xcel/Rules_gol.h \
		moc_predefs.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/bin/moc
	/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/bin/moc $(DEFINES) --include /Users/trobicho/project/otherProject/Xcellule/moc_predefs.h -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/macx-clang -I/Users/trobicho/project/otherProject/Xcellule -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtGui.framework/Headers -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib File_panel.h -o moc_File_panel.cpp

moc_GLtree.cpp: GLtree.h \
		WinGL.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QtOpenGL \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglglobal.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglcolormap.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglframebufferobject.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglfunctions.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglpixelbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglversion.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget \
		../Xcel/Xcel.h \
		../Xcel/Celtree.h \
		../Xcel/Quadtree.h \
		../Xcel/pos2D.h \
		../Xcel/cel.h \
		../Xcel/Rules.h \
		../Xcel/Loader.h \
		../Xcel/LoaderRLE.h \
		../Xcel/Rules_totalistic.h \
		../Xcel/Rules_gol.h \
		moc_predefs.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/bin/moc
	/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/bin/moc $(DEFINES) --include /Users/trobicho/project/otherProject/Xcellule/moc_predefs.h -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/macx-clang -I/Users/trobicho/project/otherProject/Xcellule -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtGui.framework/Headers -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib GLtree.h -o moc_GLtree.cpp

moc_WinGL.cpp: WinGL.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QtOpenGL \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglglobal.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglcolormap.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglframebufferobject.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglfunctions.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglpixelbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglversion.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget \
		moc_predefs.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/bin/moc
	/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/bin/moc $(DEFINES) --include /Users/trobicho/project/otherProject/Xcellule/moc_predefs.h -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/mkspecs/macx-clang -I/Users/trobicho/project/otherProject/Xcellule -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtGui.framework/Headers -I/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib WinGL.h -o moc_WinGL.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp Xcellule.h \
		MainWin.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		File_panel.h \
		GLtree.h \
		WinGL.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QtOpenGL \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglglobal.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglcolormap.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglframebufferobject.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglfunctions.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglpixelbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglversion.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget \
		../Xcel/Xcel.h \
		../Xcel/Celtree.h \
		../Xcel/Quadtree.h \
		../Xcel/pos2D.h \
		../Xcel/cel.h \
		../Xcel/Rules.h \
		../Xcel/Loader.h \
		../Xcel/LoaderRLE.h \
		../Xcel/Rules_totalistic.h \
		../Xcel/Rules_gol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MainWin.o: MainWin.cpp MainWin.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		File_panel.h \
		GLtree.h \
		WinGL.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QtOpenGL \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglglobal.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglcolormap.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglframebufferobject.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglfunctions.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglpixelbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglversion.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget \
		../Xcel/Xcel.h \
		../Xcel/Celtree.h \
		../Xcel/Quadtree.h \
		../Xcel/pos2D.h \
		../Xcel/cel.h \
		../Xcel/Rules.h \
		../Xcel/Loader.h \
		../Xcel/LoaderRLE.h \
		../Xcel/Rules_totalistic.h \
		../Xcel/Rules_gol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWin.o MainWin.cpp

Xcellule.o: Xcellule.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Xcellule.o Xcellule.cpp

GLtree.o: GLtree.cpp GLtree.h \
		WinGL.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QtOpenGL \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglglobal.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglcolormap.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglframebufferobject.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglfunctions.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglpixelbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglversion.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget \
		../Xcel/Xcel.h \
		../Xcel/Celtree.h \
		../Xcel/Quadtree.h \
		../Xcel/pos2D.h \
		../Xcel/cel.h \
		../Xcel/Rules.h \
		../Xcel/Loader.h \
		../Xcel/LoaderRLE.h \
		../Xcel/Rules_totalistic.h \
		../Xcel/Rules_gol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLtree.o GLtree.cpp

File_panel.o: File_panel.cpp File_panel.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		GLtree.h \
		WinGL.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QtOpenGL \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglglobal.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglcolormap.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglframebufferobject.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglfunctions.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglpixelbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglversion.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget \
		../Xcel/Xcel.h \
		../Xcel/Celtree.h \
		../Xcel/Quadtree.h \
		../Xcel/pos2D.h \
		../Xcel/cel.h \
		../Xcel/Rules.h \
		../Xcel/Loader.h \
		../Xcel/LoaderRLE.h \
		../Xcel/Rules_totalistic.h \
		../Xcel/Rules_gol.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QDebug \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o File_panel.o File_panel.cpp

WinGL.o: WinGL.cpp WinGL.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QtOpenGL \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglglobal.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglcolormap.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglframebufferobject.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglfunctions.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglpixelbuffer.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qglshaderprogram.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/qtopenglversion.h \
		/sgoinfre/goinfre/Perso/trobicho/Qt/5.13.0/clang_64/lib/QtOpenGL.framework/Headers/QGLWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WinGL.o WinGL.cpp

moc_MainWin.o: moc_MainWin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWin.o moc_MainWin.cpp

moc_File_panel.o: moc_File_panel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_File_panel.o moc_File_panel.cpp

moc_GLtree.o: moc_GLtree.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GLtree.o moc_GLtree.cpp

moc_WinGL.o: moc_WinGL.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WinGL.o moc_WinGL.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

